variables:
  - group: status-endpoint
  - name: service_name
    value: caas-published-cohort-definitions
  - name: short_service_name
    value: cpcd
  - name: service_base_path
    value: caas-published-cohort-definitions
