# This is an OpenAPI Specification (https://swagger.io/specification/)
# for caas-published-cohort-definitions owned by NHS Digital (https://digital.nhs.uk/)
openapi: '3.0.0'
info:
  title: 'caas-published-cohort-definitions'
  version: 'Computed and injected at build time by `scripts/set_version.py`'
  description: |
    ## Overview
    Add a fully fledged description here with markdown syntax.
    For help completing the content of your API spec, see our guidance on the minimum standard (bronze) details 
    to include [here](https://nhsd-confluence.digital.nhs.uk/display/APM/Writing+a+bronze+API+cover+page). You should also base your content on our exemplar API - [PDS FHIR](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir).
    ## Who can use this API
    To be completed.
    ## Related APIs
    To be completed.
    ## API status and roadmap
    To be completed.
    ## Service level
    To be completed.
    ## Technology
    To be completed.
    ## Network access
    To be completed.
    ## Security and authorisation
    To be completed.
    ## Environments and testing
    To be completed.
    ## Onboarding
    To be completed.

    ### Sandbox testing
    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):
    * is for early developer testing
    * only covers a limited set of scenarios
    * is stateless, so does not actually persist any updates
    * is open access, so does not allow you to test authorisation

    For details of sandbox test scenarios, or to try out the sandbox using our 'Try this API' feature, see the documentation for each endpoint.

    ### You can try out the sandbox importing our Postman collection:
    [published-cohort-definitions.postman_collection.json](../tests/postman-collection/published-cohort-definitions.postman_collection.json)
    
    ```json
    ```

    ### How to Import Postman Collections
    * Save the JSON file above
    * Launch Postman and go to the Collections section found on the left side. Then, select the "Import" option situated in the upper-left corner of the interface.
    * Within the "Import File" dialog, press the "Select Files" button and pick the Postman collection file you want to bring in.
    * After selecting the file, proceed by clicking the "Import" button to begin the import procedure.
    * Once the import process has finished, your recently imported collection should appear in the Collections tab.

    ### How to locally Import GraphQL Schema using Postman
    * Choose APIs from the sidebar, and then click on the '+' button to initiate the creation of a new API.
    * Provide a name and version for your API.
    * Click on Import under the Definition tab
    * Import the schema.gql fine in sandbox/postman/schema.gql
    * Navigate back to your GraphQL body and pick your schema from the dropdown menu. If necessary, you can refresh it by clicking on the refresh icon.
    * Start typing your query. Postman will provide autocomplete suggestions based on the data available in your newly configured GraphQL schema.


  contact:
    name: 'caas-published-cohort-definitions API Support'
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
servers:
  - url: 'https://sandbox.api.service.nhs.uk/caas-published-cohort-definitions'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/caas-published-cohort-definitions'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/caas-published-cohort-definitions'
    description: Production environment.
paths: {}
